title: "OSDev Wiki"
remote_theme: pmarsceill/just-the-docs
logo: "/Assets/logo.svg"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/osdev-wiki/wiki"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

color_scheme: osdev-wiki
plugins:
  - jekyll-feed
